// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhiwbgm_5zTvXOMgr5kXU1NCfXWqdykk',
    appId: '1:310371344155:web:6ba9256408e3fdfadf7dbe',
    messagingSenderId: '310371344155',
    projectId: 'blog-application-2c075',
    authDomain: 'blog-application-2c075.firebaseapp.com',
    storageBucket: 'blog-application-2c075.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUT4oyiEBmxX8Zb0sXZBYLv0GXK8ArsM',
    appId: '1:310371344155:android:911ae800fd682dbadf7dbe',
    messagingSenderId: '310371344155',
    projectId: 'blog-application-2c075',
    storageBucket: 'blog-application-2c075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxr_B2rmVTTXX_Y_6OGQ8eUvv6UwqILg',
    appId: '1:310371344155:ios:36f3a7f4efbc0b9bdf7dbe',
    messagingSenderId: '310371344155',
    projectId: 'blog-application-2c075',
    storageBucket: 'blog-application-2c075.appspot.com',
    iosClientId: '310371344155-dbr4pv264j8f9qav0d9uegp3gqjobq4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogSharingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxr_B2rmVTTXX_Y_6OGQ8eUvv6UwqILg',
    appId: '1:310371344155:ios:36f3a7f4efbc0b9bdf7dbe',
    messagingSenderId: '310371344155',
    projectId: 'blog-application-2c075',
    storageBucket: 'blog-application-2c075.appspot.com',
    iosClientId: '310371344155-dbr4pv264j8f9qav0d9uegp3gqjobq4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogSharingApplication',
  );
}
